### PR TITLE
feat: add lambda web adapter streaming api backend only example

### PR DESCRIPTION
**Pull request by jlonge4**
*Issue #, if available:*
N/A
*Description of changes:*

Currently there is no implementation of using the lambda web adapter to serve bedrock streaming responses back via function URL regardless of the front end used. This example will show just that.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jlonge4** [comment]
@bnusunny

**Review by bnusunny — APPROVED** [review]
LGTM

**Comment by bnusunny** [comment]
Thanks for this example. Do you mind to add a link to thins example in the project README.md file?

**Comment by jlonge4** [comment]
@bnusunny Done! It's my pleasure, perhaps it will help a person or two 😎

**Pull request merged**
